services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/images
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - .:/app
      - go-pkg-cache:/root/go/pkg

  frontend:
    image: oven/bun:1.2.19-alpine
    working_dir: /frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - frontend-node-modules:/frontend/node_modules
    command: sh -c "bun install --frozen-lockfile && bun run dev"
    depends_on:
      - backend

  database:
    image: postgres:13.14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=images
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - database:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_REGION=eu-north-1
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - minio:/data

volumes:
  database:
    driver: local
  go-pkg-cache:
    driver: local
  frontend-node-modules:
    driver: local
  minio:
    driver: local
