FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache curl bash ffmpeg && \
    curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | bash -s -- -b /usr/local/bin

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 3000

CMD ["air"]
