BEGIN;

ALTER TABLE images RENAME TO media;
ALTER TABLE media RENAME COLUMN image_data TO data;

ALTER TABLE media ADD COLUMN filename TEXT;
ALTER TABLE media ADD COLUMN width INTEGER;
ALTER TABLE media ADD COLUMN height INTEGER;
ALTER TABLE media ADD COLUMN duration_ms INTEGER;
ALTER TABLE media ADD COLUMN bitrate INTEGER;
ALTER TABLE media ADD COLUMN codec TEXT;
ALTER TABLE media ADD COLUMN framerate DOUBLE PRECISION;
ALTER TABLE media ADD COLUMN sample_rate INTEGER;
ALTER TABLE media ADD COLUMN channels INTEGER;
ALTER TABLE media ADD COLUMN cover_art BYTEA;

COMMIT;
